// Run the autogenerated loader script, that sets up the Emscripten filesystem
self.importScripts('BoydEngine.preload.js');

// Post the obtained Module object to the main loop.
// It contains the loaded datafile!
self.postMessage({
    'Module': Module
});
